---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/cortextool version
      register: cortex_tools_test_output
    - name: cortextool version
      debug:
        msg: '{{ cortex_tools_test_output.stdout }}'
