---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ cortex_tools_exe }}
  become: true
  stat:
    path: '{{ cortex_tools_exe }}'
  changed_when: false
  register: cortex_tools_binary
- when: not cortex_tools_binary.stat.exists
  block:
    - name: downloading {{ cortex_tools_url }} to {{ cortex_tools_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ cortex_tools_url }}'
        dest: '{{ cortex_tools_tmp_archive }}'
        mode: 0644
        checksum: '{{ cortex_tools_checksum }}'
    - name: mkdir {{ cortex_tools_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ cortex_tools_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ cortex_tools_tmp_archive }} into {{ cortex_tools_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ cortex_tools_tmp_archive }}'
        dest: '{{ cortex_tools_install_dir }}'
        creates: '{{ cortex_tools_exe }}'
  always:
    - name: rm {{ cortex_tools_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ cortex_tools_tmp_archive }}'
        state: absent
- name: linking {{ cortex_tools_link }} to {{ cortex_tools_exe }}
  become: true
  become_user: root
  file:
    src: '{{ cortex_tools_exe }}'
    dest: '{{ cortex_tools_link }}'
    state: link
